language: python
python:
  - "2.6"
  - "2.7"
# install dependencies
install:
  - pip install . --use-mirrors
  - pip install coveralls --use-mirrors
# run tests
script:
    - nosetests --with-coverage

after_success:
    - coveralls
